###############################################################################
# Makefile automatically generated by Code::Blocks IDE                        #
###############################################################################

# Project:          GUI application
# Project filename: D:\dev\chp\chp.cbp
# Compiler used:    GNU GCC Compiler

### Variables used in this Makefile
default_CC=mingw32-gcc.exe
default_CPP=mingw32-g++.exe
default_LD=mingw32-g++.exe
default_LIB=ar.exe
default_RESCOMP=windres.exe

### Compiler/linker options
default_GLOBAL_CFLAGS=
default_PROJECT_CFLAGS= -Os
default_GLOBAL_LDFLAGS=
default_PROJECT_LDFLAGS= -s
default_GLOBAL_INCS= -IC:/Program\ Files/CodeBlocks/include
default_PROJECT_INCS=
default_GLOBAL_LIBDIRS= -LC:/Program\ Files/CodeBlocks/lib
default_PROJECT_LIBDIRS=
default_GLOBAL_LIBS=
default_PROJECT_LIBS=

### Targets compiler flags
default_CFLAGS= $(default_PROJECT_CFLAGS) $(default_GLOBAL_CFLAGS)

### Targets linker flags
default_LDFLAGS= $(default_PROJECT_LDFLAGS) $(default_GLOBAL_LDFLAGS)

### Targets include directories
default_INCS= $(default_PROJECT_INCS) $(default_GLOBAL_INCS)

### Targets library directories
default_LIBDIRS= $(default_PROJECT_LIBDIRS) $(default_GLOBAL_LIBDIRS)

### Targets libraries
default_LIBS= $(default_PROJECT_LIBS) $(default_GLOBAL_LIBS)

###############################################################################
#         You shouldn't need to modify anything beyond this point             #
###############################################################################

### Resources used in this Makefile
default_RESOURCE=

### Objects used in this Makefile
default_OBJS=.objs/main.o 
default_LINKOBJS=$(default_OBJS)
default_DEPS=.deps/main.d 

### The targets of this project
default_BIN=chp.exe

.PHONY: all all-before all-custom all-after clean clean-custom distclean distclean-custom depend_default default-before default-after 

all: all-before default all-after


dist:
	@zip chp.cbp.zip chp.cbp Makefile main.c 

clean_default:
	@echo Cleaning target "default"...
	@$(RM) $(default_BIN) $(default_OBJS) $(default_RESOURCE) 

distclean_default:
	@echo Dist-cleaning target "default"...
	@$(RM) $(default_BIN) $(default_OBJS) $(default_DEPS) $(default_RESOURCE) 

clean: clean_default 

distclean: distclean_default 

depend_default_DIRS:
	-@if not exist ".deps\." mkdir ".deps"

depend_default: depend_default_DIRS $(default_DEPS)

depend: depend_default

default_DIRS:
	-@if not exist ".objs\." mkdir ".objs"

default: depend_default default_DIRS default-before $(default_BIN) default-after

$(default_BIN): $(default_LINKOBJS) $(default_RESOURCE)
	@echo Linking executable "chp.exe"...
	@$(default_LD) $(default_LIBDIRS) -o $(default_BIN) $(default_LINKOBJS) $(default_RESOURCE) $(default_LDFLAGS) $(default_LIBS) -mwindows


.deps/main.d: main.c
	@echo Calculating dependencies for "main.c"...
	@$(default_CC) -MM $(default_CFLAGS) -MF .deps/main.d -MT .objs/main.o $(default_INCS) main.c

.objs/main.o: .deps/main.d
	@echo Compiling "main.c"...
	@$(default_CC) $(default_CFLAGS) $(default_INCS) -c main.c -o .objs/main.o



